export enum RootRoutes {
  SPLASH_SCREEN = "SPLASH_SCREEN",
  TAB_NAVIGATOR = "TAB_NAVIGATOR",
}

export enum TabRoutes {
  DASHBOARD = "DASHBOARD",
  SEARCH_SCREEN = "SEARCH_SCREEN",
  MENU_SCREEN = "MENU_SCREEN"
}